### ISSUE TITLE
Introduce interactive CLI for easier testing

### ISSUE THREAD

**Issue by dario-chiappetta** [dario-chiappetta/Due#31]
```
AS A Due user
IN ORDER TO try out the software as easily as possible
I WANT TO have a console based agent that needs no extra resources
```

**Rationale**
Currently, the only way to deploy Due is through its XMPP interface, which requires access to an external chat server. We want a user to be able to try out an agent with as little external dependencies as possible.

This is also an opportunity to refactor the role of the Agent class, which currently does little more than passing information to/from a Brain class.

**TODO**

- [x] Refactor the role of the Agent interface
- [x] Introduce `serve` package porting current XMPP agent
- [x] Add a `serve.cli` for dialog over CLI
- [x] Update README to use ConsoleAgent (move XMPP example to docs)
