### ISSUE TITLE
Include Toy corpus for easier testing

### ISSUE THREAD

**Issue by dario-chiappetta** [dario-chiappetta/Due#32]
AS A Due user
IN ORDER TO try out the software as easily as possible
I WANT TO import a toy corpus that needs no extra resources

**Rationale**
Currently there are no pre-trained agents to be imported, and the size of the available corpora is a barrier to a quick setup of the agent. We want a user to be able to try out an agent with as little external dependencies as possible.

**TODO**
- [x] Change serialization format to JSON/YAML
- [x] Add a built-in toy corpus
- [x] Update README to the toy corpus
